### ISSUE TITLE
Windows Terminal Theme

### ISSUE THREAD

**Issue by andrevandal** [tuguldurio/monokai-sweet#1]
Hi, I love your theme!

would you mind making a windows terminal version?

Thanks!

**Comment by tuguldurio** [comment]
sorry for late.
can you clarify what do you mean by "windows terminal"?

**Comment by andrevandal** [comment]
No problem hehe
The new console on windows:
https://github.com/microsoft/terminal/
https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab
