### ISSUE TITLE
Unpublished

### ISSUE THREAD

**Issue by spaaacetoast** [tuguldurio/monokai-sweet#2]
Hey Man,

I love this theme! But i now see it is unpublished on the vscode marketplace :(
Are there any plans continueing it?

**Comment by tuguldurio** [comment]
Yes. 
I was planning to come up with new name "Monokai Aora".
It may take few days to republish, and current source code will move to new repo.
Sorry for inconvenience.

**Comment by spaaacetoast** [comment]
Cool! Thanks for the response 😁
