### ISSUE TITLE
Abandoned Project?

### ISSUE THREAD

**Issue by Eventyret** [tuguldurio/monokai-sweet#3]
Hey, @tuguldurio just wanted to check has this project been abandoned or anything since it was removed from market place.
I don't mind keep it up to date or change a few things with it as it's my main go-to theme.
Let me know.

**Comment by tuguldurio** [comment]
you can modify however you want.
project will continue under https://github.com/tuguldurio/monokai-aora and https://marketplace.visualstudio.com/items?itemName=tuguldurio.monokai-aora.
had problem with vsce devazure now things are solved.
